services:
  ayet-hadis-bot:
    build: .
    image: ghcr.io/mehmetext/ayet_hadis_bot:main
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - bot-data:/app/data

volumes:
  bot-data:
